### ISSUE TITLE
Movimiento y actualización de vecinos

### ISSUE THREAD

**Issue by GMaiolo** [niconj/Entrule#2]
La ficha roja solo camina por los casilleros donde caminó la azul

**Comment by GMaiolo** [comment]
Script Inicialización: ![inicializacion](https://cloud.githubusercontent.com/assets/9776436/6649853/41f0dd2e-c9d5-11e4-83f0-68657a18d1e0.jpg)

Script Movimiento: ![movimiento](https://cloud.githubusercontent.com/assets/9776436/6649851/41b32ed4-c9d5-11e4-9a86-489f269fa80f.jpg)

Script PlayerScript: ![playerscript](https://cloud.githubusercontent.com/assets/9776436/6649852/41d5cade-c9d5-11e4-8c7b-28b6ed1b2e9c.jpg)

**Comment by niconj** [comment]
Llegué al problema que tenias antes con las variables que vuelven a cero. Si quiero mover la roja a un casillero donde nunca estuvo la azul me marca como que el turno es del azul, en cambio si quiero moverla a una casilla donde antes estuvo la azul, me marca el turno para los rojos...  sufrimiento.

**Comment by GMaiolo** [comment]
Fixeado con la nueva versión.
